# Analyzer and lint configuration for baseline code quality checks.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    use_super_parameters: true
